<?php
/***************************************************************************
 *                          lang_faq.php [Turkish]
 *                            -------------------
 *   begin                : Wednesday Oct 3, 2001
 *   copyright            : (C) 2001 The phpBB Group
 *   email                : support@phpbb.com
 *
 *   $Id: lang_faq.php,v 1.4 2001/12/15 16:42:08 psotfx Exp $
 *
 *
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/
//
// Translation by:
//
// ESQARE (taNGo) :: admin@turkiyeforum.com :: http://www.phpbbturkey.com :: http://www.turkiyeforum.com
//
// For questions and comments use: admin@turkiyeforum.com
//

$faq[] = array('--','Giriþ ve Kayýt sorunlarý');
$faq[] = array('Neden giriþ yapamýyorum?','Kayýt oldunuz mu? Giriþ yapabilmek için önceden kayýt olmanýz gerek. Yoksa siteden yasaklandýnýz mý (o halde bu anlamda bir mesaj görmeniz gerekir)? Eðer öyleyse, site yöneticisiyle (webmaster) veya site yöneticisiyle (yönetici) irtibata geçip sebebini sorabilirsiniz. Eðer kayýt olduysanýz ve yasaklanmýþ olmamanýza raðmen giriþ yapamýyorsanýz, tekrar tekrar kullanýcý adýnýzý ve þifrenizi kontrol edin. Genelde hata burada oluyor. Sorun bu deðilse site yönetimi ile iletiþime geçin, belki site için yanlýþ ayar yapmýþ olabilirler.');
$faq[] = array('Neden kayýt olmam gerekiyor?','Kayýt olmanýza gerek olmayabilirdi aslýnda. Mesaj gönderebilmek için kaydýn þart olmasý, site yöneticisinin (yönetici) kararýna baðlý. Ayrýca kayýt olunca bazý özel imkanlara ulaþabilirsiniz. Örneðin mesajlarýnýzýn yanýnda kedinize ait küçük bir resim (avatar) gösterme, özel mesaj gönderme, tanýdýðýnýz kullanýcýlara mail gönderme veya kullanýcý gruplarýna katýlma imkanlarýna misafir kullanýcýlar sahip deðildir. Kayýt iþlemi çok basit olduðu için kayýt olmanýz önerilir.');
$faq[] = array('Neden otomatik olarak çýkýþým yapýlýyor?','Giriþ sayfasýnda gördüðünüz <i>Her ziyaretimde otomatik giriþ yap</i> kutucuðunu iþaretlemediðiniz sürece, site sizi sadece belirli bir süre için giriþ yapmýþ kabul eder. Böylece kaydýnýzýn baþkalarý tarafýndan kullanýlmasý önlenir. Giriþinizin devamlý kalmasý için, bu komutu seçmeniz yeterlidir. Fakat baþka þahýslarýnda kullandýðý (örn. herhangi bir kütüphaneye, internet kafeye, üniversiteye vs. ait) bir bilgisayardan giriþ yapýyorsanýz, bu komutu seçmemeniz önerilir.');
$faq[] = array('Çevrimiçi kullanýcý listesinde kullanýcý adýmýn görünmesini nasýl önleyebilirim?','Profil sayfanýza gidip <i>Çevrimiçi olduðumu gizle</i> seçeneðini bulabilirsiniz. Buradan <i>Evet</i> \'i seçince çevrimiçi olduðunuzu sadece site yöneticileri ve kendiniz görebilirsiniz. Bu durumda gizli kullanýcý olarak sayýlýrsýnýz.');
$faq[] = array('Þifremi unuttum!','Telaþa kapýlmayýn! Eski þifrenizi öðrenmek mümkün olmasa bile, yerine deðiþik bir þifre alabilirsiniz. Giriþ sayfasýný açýp <u>Þifremi unuttum</u> baðlantýsýna týklayýn ve tarif edilen iþlemleri uygulayýn. Kýsa sürede tekrar çevrimiçi olduðunuzu göreceksiniz');
$faq[] = array('Kayýt oldum ama giriþ yapamýyorum!','Ýlk önce kullanýcý adýnýzý ve þifrenizi doðru yazdýðýnýzý temin edin. Doðru yazýlmýþsa, iki sebep daha olabilir. Eðer COPPA destekleniyorsa ve kaydýnýz esnasýnda <u>13 yaþýndan küçüðüm</u> linkini týkladýysanýz, tarif edilen iþlemleri uygulamanýz gerek. Sebep bu deðilse, kaydýnýzýn onaylanmasý gerekebilir. Bazý forum siteleri tüm yeni kayýtlarýn onaylanmasýný þart koþar. Giriþ yapabilmeniz için ya kendiniz yada site yöneticisi tarafýndan kaydýnýz onaylanmalýdýr. Bu durumda onay gerekçesi, kaydýnýz esnasýnda size bildirilmiþ olmalý. Bu doðrultuda bir e-posta aldýysanýz, tarif edilen iþlemleri uygulamanýz gerek. Eðer böyle bir e-posta almadýysanýz, verdiðiniz e-posta adresinin doðru olup olmadýðýný kontrol edin. Onay gerekçesinin sebebi, <i>kötü amaçlý</i> kullanýcýlarýn anonim kalýp forum sitesini suistimal etmelerini önlemektir. Verdiðiniz e-posta adresinin doðru olduðundan eminseniz, site yöneticisiyle irtibata geçmeniz gerekir.');
$faq[] = array('Daha önce kayýt olmuþtum ama artýk giriþ yapamýyorum?!','Bunun en olasý sebebi hatalý kullanýcý adý veya þifre giriþidir (kayýt olduktan sonra aldýðýnýz e-postaya bakýp kontrol edin). Belkide site yöneticisi kaydýnýzý herhangi bir sebepten dolayý silmiþ olabilir. Forumlara hiç mesaj gönderdiniz mi? Veritabanýnýn kapladýðý alaný küçük tutmak için, mesaj göndermeyen kullanýcýlarýn kaydý genelde belirli bir süre sonra silinir. Tekrar kaydolmayý deneyin ve tartýþmalara katýlýn.');
$faq[] = array('--','Kullanýcý Seçenekleri ve ayarlarý');
$faq[] = array('Kullanýcý ayarlarýmý nasýl deðiþtirebilirim?','Eðer kaydolduysanýz bütün ayarlarýnýz veritabanýna kaydedilir. Ayarlarýnýzý deðiþtirmek için (genelde sayfalarýn üst kýsmýnda bulunan) <u>Profil</u> linkini týklayýn. Ayarlarýnýz buradan deðiþtirilir');
$faq[] = array('Gösterilen zamanlar yanlýþ!','Gösterilen zamanlar büyük bir ihtimalle doðrudur. Fakat gördüðünüz zaman, bulunduðunuz yerin zaman diliminden farklý olabilir. Bu durumda, <u>Profil</u> linkini týklayýp kendiniz için geçerli zaman dilimini seçmeniz gerekir, örn. London, Paris, New York, Sydney vs. Çoðu seçenekler için geçerli olduðu gibi, zaman dilimini deðiþtirme imkanýda sadece kayýtlý kullanýcýlara verilmiþtir. Eðer kayýtlý deðilseniz, kaydolmanýn tam zamaný (kelime oyununu baðýþlayýn)!');
$faq[] = array('Deðiþik bir zaman dilimi seçtim ama saatler hala yanlýþ!','Doðru zaman dilimini seçtiðinizden eminseniz ve saat hala yanlýþ gösteriliyorsa, bunun en olasý sebebi günýþýðýndan yararlanma deðiþimleri olabilir. Örn. yaz aylarýnda görülen saatler, bulunduðunuz ülkenin gerçek saatinden bir saat ileri veya geri olabilir. Forum sitesi bu deðiþimleri dikkate almaz.');
$faq[] = array('Konuþtuðum dil listede yok!','Bunun en olasý sebepleri, ya site yöneticisinin konuþtuðunuz lisaný destekleyen uzantýyý kurmuþ olmayýþý, ya da bu sitenin konuþtuðunuz lisana henüz çevrilmiþ olmayýþýdýr. Site yöneticilerine baþvurup, kendi lisanýnýzý destekleyen uzantýyý kurmalarýný rica edin. Eðer böyle bir uzantý yoksa, siteyi kendi dilinize çevirmekte özgürsünüz. Bu konuda daha geniþ bilgi için sayfalarýn alt kýsmýnda görülen phpBB Group linkini týklayýn.');
$faq[] = array('Kullanýcý adýmýn altýnda resim göstermek için ne yapmalýyým?','Mesajlarýn görüntülendiði sayfalarda kullanýcý adlarýnýn altýnda iki tür resim görebilirsiniz. Birincisi, kullanýcý rütbenizi gösterir ve genelde gönderdiðiniz mesaj sayýsýna baðlý olarak belirli bir sayýda yýldýz veya kare þeklindedir. Bunun altýnda avatar denen biraz daha büyük bir resim görebilirsiniz. Bu resim genelde kullanýcýya ait ve özeldir. Avatar kullanma imkanýný site yöneticisi saptar. Ayrýca avatar\'larýn ne þekilde kullanýlabileceðinide saptar. Avatar kullanamýyorsanýz, site yöneticisine baþvurup bu imkaný ne sebepten iptal ettiðini öðrenebilirsiniz (bunun önemli bir sebebi olduðundan eminiz!)');
$faq[] = array('Kullanýcý rütbemi nasýl deðiþtirebilirim?','Genelde kullanýcý rütbenizi doðrudan deðiþtirmeniz mümkün deðildir (kullanýcý rütbesi, gönderdiðiniz mesajýn yanýnda bulunan isminizin altýnda ve kullanýcý profili sayfasýnda görülür). Çoðu forum sitesinde kullanýcý rütbeleri, gönderilen mesajlarýn sayýsýný veya yetkili üyeleri belirlemek için kullanýlýr, örn. yöneticiler veya site yöneticileri özel bir rütbeye sahip olabilir. Lütfen gereksiz yere mesaj gönderipte rütbenizi yükseltmeye çalýþmayýn, elde edeceðiniz tek sonuç, yöneticilerin mesajlarýnýzýn sayýsýný düþürmesi olacaktýr.');
$faq[] = array('Bir kullanýcýya ait e-posta linkini týklayýnca giriþ yapmam isteniyor?','Üzgünüz fakat e-posta formuyla maalesef sadece kayýtlý kullanýcýlar e-posta gönderebiliyor (eðer yönetici bu özelliði aktif ettiyse). Bunun sebebi, e-posta sisteminin anonim kullanýcýlar tarafýndan suistimal edilmesini önlemektir.');
$faq[] = array('--','Mesaj Gönderme');
$faq[] = array('Bir foruma yeni bir baþlýk nasýl gönderilir?','Çok kolay, forumu veya baþlýðý görüntüleme sayfasýnda <i>Yeni Baþlýk Gönder</i> düðmesini týklayýn. Yeni mesaj göndermeden önce kayýt olmanýz gerekebilir. Forum ve baþlýk sayfalarýnýn alt kýsmýnda yapabileceðiniz bütün iþlemlerin listesini görebilirsiniz (örn. <i>Bu forumda yeni baþlýklar gönderebilirsiniz</i> vs. gibi).');
$faq[] = array('Bir mesajý nasýl silebilir veya düzenleyebilirim?','Site yöneticisi veya moderatör olmadýðýnýz sürece, sadece kendinize ait mesajlarý düzenleyebilir veya silebilirsiniz. Gönderdiðiniz bir mesajý <i>Mesajý Düzenle</i> düðmesini týklayarak düzenleyebilirsiniz (bu imkan bazen sadece belirli bir süre için mevcuttur). Mesajýnýza birileri cevap göndermiþse eðer, mesajýnýzýn altýnda metni kaç defa düzenlediðinizi gösteren kýsa bir yazý göreceksiniz. Mesajýnýz henüz yanýtlanmamýþsa, bu not görülmez. Ayrýca mesajýnýz site yöneticileri veya moderatörler tarafýndan düzenlenincede bu yazý görünmez (yöneticilerin böyle bir durumda metnin hangi kýsmýný ne sebepten dolayý düzenlediklerini yazmalarý önerilir). Bir mesaja cevap geldikten sonra normal kullanýcýlar tarafýndan silinemez.');
$faq[] = array('Mesajýma bir imza nasýl eklerim?','Herhangi bir mesaja imzanýzý ekleyebilmek için önce <i>Profil</i> sayfanýza girip bir imza hazýrlamanýz gerek. Daha sonra mesaj gönderme formunun alt kýsmýndaki <i>Ýmzamý ekle</i> seçeneðini seçip mesajýnýza imzanýzý ekleyebilirsiniz. Gönderdiðiniz bütün mesajlara genel bir ayar olarak imzanýzýn eklenmesini istiyorsanýz, <i>Profil</i> sayfasýndaki seçeneði týklayýn. Buna raðmen dilediðiniz her mesaj için imzanýzýn eklenmesini önleyebilirsiniz (mesaj gönderme formunda <i>Ýmzamý Ekle</i> seçeneðinin iþaretini kaldýrmanýz yeterlidir)');
$faq[] = array('Nasýl bir anket oluþtururum?','Anket oluþturmak kolaydýr, yeni bir baþlýk gönderirken (veya bir baþlýðýn ilk mesajýný düzenlerken (bu tabiki yetkinize baðlýdýr)), mesaj gönderme formunun altýnda <i>Anket Ekle</i> formunu göreceksiniz (böyle bir formu göremiyorsanýz, anket ekleme yetkiniz yok demektir). Anket sorusunu ve en az iki tane anket þýkký eklemeniz gerekir. Anket þýkký eklemek için <i>Bu Þýkký Ekle</i> düðmesini týklayýn. Ayrýca anketin gösterim süresinide belirleyebilirsiniz, 0 süresiz demektir. Eklenebilecek anket þýklarýnýn sayýsý sýnýrlýdýr. Bu sýnýrý site yöneticisi belirler');
$faq[] = array('Bir anketi nasýl deðiþtirir veya silerim?','Anketlerde mesajlar gibi sadece gönderen kullanýcý, moderatör veya site yöneticisi tarafýndan deðiþtirilebilir. Bir anketi deðiþtirmek için, baþlýðýn ilk mesajýný týklayýn (ilgili anket daima bu mesaja baðlýdýr). Ankete henüz katýlan olmadýysa, hazýrlayan kullanýcý tarafýndan deðiþtirilebilir veya silinebilir. Ankete katýlan olmuþsa, sadece forum ve site yöneticileri tarafýndan deðiþtirilebilir veya silinebilir. Böylece bir süre sonra þýklarý deðiþtirip anket sonuçlarýný saptýrma olanaðý kalmaz');
$faq[] = array('Neden bir foruma eriþimim yok?','Bazý forumlar sadece belirli kullanýcýlara veya kullanýcý gruplarýna açýk olabilir. Mesajlarý okumak, görüntülemek, göndermek için vs. özel yetki gerekebilir. Bu yetkiyi sadece ilgili moderatör veya site yöneticisi verebilir, bu kiþilere baþvurmalýsýnýz.');
$faq[] = array('Neden anketlere oy veremiyorum?','Anketlere sadece kayýtlý kullanýcýlar oy verebilir (böylece hile yapma olanaðý önlenmiþ olur). Eðer kayýt olmanýza raðmen hala anketlere oy veremiyorsanýz, gerekli yetkilere sahip deðilsiniz demektir.');
$faq[] = array('--','Biçimlendirme ve Baþlýk Tipleri');
$faq[] = array('BBCode nedir?','BBCode HTML\'in özel bir uygulamasýdýr. Forum\'a yazdýðýnýz mesajlarda BBCode kullanabilme imkanýný site yöneticisi saptar. Ayrýca mesaj gönderme formundaki seçenekler sayesinde dilediðiniz mesajlarda BBCode\'ý iptal etmeniz mümkündür. BBCode, HTML\'e benzer tarzdadýr fakat tag\'ler &lt; ve &gt; yerine köþeli parantez içine alýnýr: [ ve ]. Ayrýca nelerin nasýl görüntülendiði daha iyi kontrol edilebilir. BBCode hakkýnda daha geniþ bilgiler için, mesaj gönderme sayfasýndan ulaþabileceðiniz rehbere bakýnýz.');
$faq[] = array('HTML kullanabilir miyim?','Site yöneticisinin izin vermesine baðlýdýr, ilgili ayarlarýn tümünü o kontrol eder. Eðer izin verilmiþse, büyük ihtimalle sadece bazý tag\'lerin çalýþtýðýný göreceksiniz. Böyle olmasý <i>güvenlik</i> içindir. Amaç, site görüntüsünün bozulmasýný veya daha deðiþik sorunlarýn meydana gelmesini önlemektir. Ýzin verilmiþ olsa bile, mesaj gönderme formundaki seçenekler sayesinde dilediðiniz mesajlarda HTML\'i iptal etmeniz mümkündür.');
$faq[] = array('Ýfadeler nedir?','Ýfadeler veya Semboller, belirli duygu ifadelerini vermek için kullanýlan iþaretlerdir. Metinde küçük resimler halinde görüntülenir. Örn. :) mutlu, :( ise üzgün anlamýndadýr. Kullanabileceðiniz ifadelerin listesini mesaj gönderme formunda görebilirsiniz. Ýfadeleri aþýrý derecede kullanmamaya özen gösterin, metin yoksa okunmaz hale gelebilir. Bu durumda yönetici ifadeleri veya mesajýnýzý tamamýyla silmeye karar verebilir');
$faq[] = array('Resim gönderebilir miyim?','Gönderdiðiniz mesajla beraber resimde görüntülenebilir. Fakat þu anda siteye doðrudan resim göndermek mümkün deðildir. Bu yüzden umuma açýk bir web sunucusunda kayýtlý bir resme link vermeniz gerek, örn. http://www.umuma-acik-sunucu.net/resim.gif . Kendi bilgisayarýnýzda bulunan bir resme link vermeniz mümkün deðil (bilgisayarýnýz umuma açýk bir web sunucu olmadýðý sürece). Ayrýca, umuma açýk olmayan ve sadece þifreyle ulaþýlan resimlere link vermek mümkün deðildir (örn. hotmail veya yahoo mailboxlarýnda vs. kayýtlý resimler). Resim görüntülemek için, BBCode\'ýn [img] tag\'ini yada (müsaade verilmiþse) HTML kullanabilirsiniz.');
$faq[] = array('Duyurular nedir?','Duyurular çoðu zaman önemli bilgileri içerir, en kýsa zamanda okumanýzý öneririz. Duyurular, ilgili forumun her sayfasýnýn baþýnda görülür. Duyuru gönderebilmeniz için bu yetkiye sahip olmanýz gerek. Yetkilerinizi ise site yöneticisi saptar.');
$faq[] = array('Sabit baþlýklar nedir?','Sabit baþlýklar, ilgili forumun ilk sayfasýnda, duyurularýn hemen altýnda görülür. Çoðu zaman önemli bilgileri içerirler, mümkünse okumanýzý öneririz. Duyurular için geçerli olduðu gibi, herhangi bir foruma sabit baþlýk göndermek için gereken yetkileri site yöneticisi saptar.');
$faq[] = array('Kilitli baþlýklar nedir?','Bu baþlýklarý moderatör veya site yöneticisi kilitler. Kilitli baþlýklarý yanýtlamak mümkün deðildir, içerdikleri anketler otomatik olarak sona erir. Baþlýklar birçok nedenlerden dolayý kilitlenmiþ olabilir.');
$faq[] = array('--','Kullanýcý Seviyeleri ve Gruplarý');
$faq[] = array('Yöneticiler nedir?','Yöneticiler, sitenin her bölümünde en çok yetkiye sahip olan þahýslardýr. Bu kiþiler, sitenin her türlü iþlevini kontrol edebilir: izin verme, yetkilendirme, kullanýcý yasaklama, kullanýcý gruplarý yaratma, moderatör yetkilerini verme vs. Ayrýca bütün forumlarda moderatör yetkilerine sahiptirler.');
$faq[] = array('Moderatörler nedir?','Moderatörler, günlük olarak forumun çalýþmasýný kontrol eden þahýslar veya gruplardýr. Baþlýklarý deðiþtirme ve silme yetkisine sahip olabilirler. Ayrýca moderatör olduklarý forumdaki baþlýklarý kilitleyebilir, taþýyabilir, silebilir ve bölebilirler. Genelde moderatörlerin görevi, <i>off-topic</i>, yani baþlýk konusuyla ilgisi olmayan yanýtlarýn veya hakaret ve saldýrý niteliðinde metinlerin gönderilmesini önlemektir.');
$faq[] = array('Kullanýcý gruplarý nedir?','Kullanýcý gruplarý, site yöneticilerinin kullanýcýlarý grup halinde ayýrabilmesi için öngörülen bir yöntemdir. Her kullanýcý (çoðu sitelerden farklý olarak) birçok gruba üye olabilir. Bu þekilde site yöneticileri belirli kullanýcýlara rahatlýkla moderatör yetkilerini veya özel forumlara ulaþma yetkisini vs. verebilir');
$faq[] = array('Bir kullanýcý grubuna nasýl katýlabilirim?','Bir kullanýcý grubuna katýlabilmek için, herhangi bir sayfa üzerindeki kullanýcý gruplarý linkine týklayýn. Kullanýcý gruplarýnýn listesini göreceksiniz. Gruplarýn tümü <i>eriþime açýk</i> olmayabilir, bazýlarý kilitli veya gizli olabilir. Grup açýk ise, ilgili linke týklayarak üye olmak için istekte bulunabilirsiniz. Ýsteðinizin kullanýcý grubu moderatörü tarafýndan onaylanmasý gerek, örneðin isteðinizin nedenini sorabilir. Ýsteðiniz reddedilirse grup moderatörünü lütfen rahatsýz etmeyin, bunun nedenleri olsa gerek.');
$faq[] = array('Bir kullanýcý grubunun moderatörü olmak için ne yapmam gerek?','Kullanýcý gruplarý site yöneticisi tarafýndan açýlýr. Site yöneticisi ayný zamanda her grubun moderatörünü saptar. Eðer yeni bir kullanýcý grubu açmak istiyorsanýz, ilk önce site yöneticisiyle irtibata geçmeniz gerek, kendisine özel mesaj göndermeyi deneyin.');
$faq[] = array('--','Özel Mesajlar');
$faq[] = array('Özel mesajlar gönderemiyorum!','Bunun üç sebebi olabilir; henüz kayýt olmamýþ veya giriþ yapmamýþsýnýz, veya site yöneticisi bütün site için özel mesajlarý iptal etmiþ. Üçüncü olanak ise: site yöneticisi sizin bu imkaný kullanmanýzý önlemiþ olabilir, bu durumda kendisine nedenini sormanýz gerekir.');
$faq[] = array('Ýstemediðim özel mesajlarý almaya devam ediyorum!','Ýleride özel mesajlar sistemine belirli kiþilerden gelen mesajlarý iptal etme imkanýný ekleyeceðiz. Þimdilik herhangi bir þahýstan istemediðiniz özel mesajlar alýyorsanýz, site yöneticisine baþvurun. O herhangi bir kullanýcýyý özel mesaj göndermekten men edebilir.');
$faq[] = array('Bu forum sitede herhangi birinden spam e-posta aldým!','Üzgünüz. Aslýnda bu sitenin sunduðu email gönderme iþlevi bundan korunmak için birçok önlemi almýþ bulunuyor. Aldýðýnýz spam e-postanýn bir kopyasýný site yöneticisine gönderin. Özellikle aldýðýnýz emailin baþlýk kýsmýný (to (kime), subject (konu) vs.) iletmeyi unutmayýn, bu kýsýmda emaili gönderen kullanýcý hakkýnda bilgiler bulunur. Site yöneticisi bu bilgilerle meseleyi takip edebilir.');

//
// These entries should remain in all languages and for all modifications
//
$faq[] = array('--','phpBB 2 Konularý');
$faq[] = array('Bu forum sitesini kim yazdý?','Bu yazýlým (deðiþtirilmemiþ haliyle) <a href="http://www.phpbb.com/" target="_blank">phpBB Group</a> tarafýndan üretilmiþ ve genel daðýtýma çýkarýlmýþtýr. Tüm eser haklarý phpBB Group\'a aittir. Bu eser, GNU General Public Licence antlaþmasýna uygun olarak eriþime açýlmýþtýr. Bu antlaþmaya uyma þartýyla ücretsiz daðýtýlabilir. Daha detaylý bilgiler için linke göz atýn.');
$faq[] = array('Aradýðým X özellik neden yok?','Bu yazýlým phpBB Group tarafýndan yazýlmýþ ve daðýtýma çýkarýlmýþtýr. Eðer herhangi bir özelliðin eksik olduðunu düþünüyorsanýz, lütfen phpbb.com sitesini ziyaret edip phpBB Group\'un ilgili düþüncelerini öðrenin. Lütfen phpbb.com sitesindeki forumlara yazýp yeni bir özellik isteðinde bulunmayýn. phpbb Group sourceforge aracýlýðýyla yeni özellikler ekler. Lütfen ilgili forumlarý gezip ilk önce phpBB Group\'un herhangi bir özellikle ilgili tutumunu öðrenin ve daha sonra burada tarif edilen yöntemle baþvuruda bulunun.');
$faq[] = array('Bu siteyle ilgili hukuki sorunlar için veya suistimal durumlarda kime baþvurabilirim?','Site yöneticisine baþvurmanýz önerilir. Site yöneticisinin kim olduðunu öðrenemezseniz, ilk önce moderatörlerden biriyle irtibata geçip, kime yazmanýz gerektiðini öðrenin. Herhangi bir yanýt alamadýðýnýz takdirde, site sahibine baþvurun (whois aramasýyla sitenin sahibini öðrenebilirsiniz) veya (eðer site ücretsiz hizmet veren sitelerde çalýþtýrýlýyorsa, örn. yahoo, free.fr, f2s.com vs.) sitenin yönetimine veya suistimal konularýyla ilgilenen þubesine baþvurun. phpBB Group\'un bu sitenin nasýl, nerede ve kimler tarafýndan çalýþtýrýldýðýný kontrol etmediðini ve herhangi bir þekilde bundan sorumlu olmadýðýný lütfen dikkate alýn. phpbb.com sitesiyle veya phpBB yazýlýmýyla doðrudan ilgisi olmayan herhangi bir hukuki konuda (ihtiyati tedbir, mali sorumluluk, iftira vs.) phpBB Group\'la irtibata geçmek tamamen anlamsýzdýr. Bu yazýlýmýn herhangi üçüncü þahýslar tarafýndan kullanýmýyla ilgili phpBB Group\'a e-posta yazarsanýz, ya çok kýsa bir cevap alýrsýnýz ya da hiç cevap alamazsýnýz.');

//
// This ends the FAQ entries
//

?>