// PT Brazilian variables by Fernando Soares - www.fernandosoares.com.br

tinyMCE.addI18n('pt.advanced',{
style_select:"Estilos",
font_size:"Tamanho",
fontdefault:"Fonte",
block:"Formato",
paragraph:"Parágrafo",
div:"Div",
address:"Endereço",
pre:"Pré-formatado",
h1:"Cabeçalho 1",
h2:"Cabeçalho 2",
h3:"Cabeçalho 3",
h4:"Cabeçalho 4",
h5:"Cabeçalho 5",
h6:"Cabeçalho 6",
blockquote:"Blockquote",
code:"Código",
samp:"Mostrar código",
dt:"Definição de termos",
dd:"Definição de descrições",
bold_desc:"Negrito (Ctrl+B)",
italic_desc:"Itálico (Ctrl+I)",
underline_desc:"Sublinhado (Ctrl+U)",
striketrough_desc:"Tachado",
justifyleft_desc:"Alinhar à esquerda",
justifycenter_desc:"Centralizar",
justifyright_desc:"Alinhar à direita",
justifyfull_desc:"Justificar",
bullist_desc:"Lista não ordenada",
numlist_desc:"Lista ordenada",
outdent_desc:"Remover identação",
indent_desc:"Identar",
undo_desc:"Desfazer (Ctrl+Z)",
redo_desc:"Refazer (Ctrl+Y)",
link_desc:"Inserir/editar link",
unlink_desc:"Remover link",
image_desc:"Inserir/editar imagem",
cleanup_desc:"Limpar código",
code_desc:"Editar código HTML",
sub_desc:"Sub-índice",
sup_desc:"Super-índice",
hr_desc:"Inserir régua horizontal",
removeformat_desc:"Remover formato",
custom1_desc:"Sua descrição personalizada;",
forecolor_desc:"Escolher cor do texto",
backcolor_desc:"Escolher cor do fundo",
charmap_desc:"Inserir caracteres personalizados",
visualaid_desc:"Mudar diretrizes/elementos invisíveis",
anchor_desc:"Inserir/editar âncora",
cut_desc:"Cortar",
copy_desc:"Copiar",
paste_desc:"Colar",
image_props_desc:"Propriedades da imagem",
newdocument_desc:"Novo documento",
help_desc:"Ajuda",
blockquote_desc:"Blockquote",
clipboard_msg:"Copiar/Recortar/Colar não estão disponíveis no Mozilla e Firefox. \r\n Deseja obter maiores informações?",
path:"Caminho",
newdocument:"Deseja criar novo documento? Esta ação irá remover todo o conteúdo.",
toolbar_focus:"Ir para a ferramenta de botões - Alt + Q, Ir ao editor - Alt+Z, Ir ao caminho do elemento - Alt + X",
more_colors:"Mais cores"
});