// PT Brazilian variables by Fernando Soares - www.fernandosoares.com.br

tinyMCE.addI18n('pt.advanced_dlg',{
about_title:"Sobre o TinyMCE",
about_general:"Sobre",
about_help:"Ajuda",
about_license:"Licença",
about_plugins:"Plugins",
about_plugin:"Plugin",
about_author:"Autor",
about_version:"Versão",
about_loaded:"Plugins carregados",
anchor_title:"Inserir/editar âncora",
anchor_name:"Nome da âncora",
code_title:"Editor de código HTML",
code_wordwrap:"Autoajuste de linha",
colorpicker_title:"Escolha uma cor",
colorpicker_picker_tab:"Seletor",
colorpicker_picker_title:"Seletor de cores",
colorpicker_palette_tab:"Paleta",
colorpicker_palette_title:"Paleta de cores",
colorpicker_named_tab:"Com nome",
colorpicker_template_tab:"Template",
colorpicker_named_title:"Cores com nome",
colorpicker_template_title:"Cores do template",
colorpicker_color:"Cor:",
colorpicker_name:"Nome:",
charmap_title:"Escolha um caractere personalizado",
image_title:"Inserir/editar imagem",
image_src:"URL da imagem",
image_alt:"Descrição da imagem",
image_list:"Lista da imagem",
image_border:"Borda",
image_dimensions:"Dimensões",
image_vspace:"Espaço Vertical",
image_hspace:"Espaço Horizontal",
image_align:"Alinhamento",
image_align_baseline:"Linha de base",
image_align_top:"Superior",
image_align_middle:"Meio",
image_align_bottom:"Inferior",
image_align_texttop:"Texto superior",
image_align_textbottom:"Texto inferior",
image_align_left:"Esquerda",
image_align_right:"Direita",
link_title:"Inserir/editar link",
link_url:"URL do link",
link_target:"Destino",
link_target_same:"Abrir o link na mesma janela",
link_target_blank:"Abrir o link em uma nova janela",
link_titlefield:"Título",
link_is_email:"A URL informada parece ser um endereço de e-mail, deseja inserir o prefixo mailto:?",
link_is_external:"A URL informada parece ser um link externo, deseja inserir o prefixo http://:?",
link_list:"Lista de link"
});